### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by matheusdavidson** [wagoid/busca-cep#1]
Erro ao iniciar(node server)

```
C:\Users\MatheusDavidson\www\rcl\server\node_modules\busca-cep\index.js:6                          
const CEP_SIZE = 8;                                                                                
^^^^^                                                                                              
SyntaxError: Use of const in strict mode.                                                          
    at exports.runInThisContext (vm.js:73:16)                                                      
    at Module._compile (module.js:443:25)                                                          
    at Object.Module._extensions..js (module.js:478:10)                                            
    at Module.load (module.js:355:32)                                                              
    at Function.Module._load (module.js:310:12)                                                    
    at Module.require (module.js:365:17)                                                           
    at require (module.js:384:17)                                                                  
    at Object.<anonymous> (C:\Users\MatheusDavidson\www\rcl\server\api\cep\cep.controller.js:3:16) 
    at Module._compile (module.js:460:26)                                                          
    at Object.Module._extensions..js (module.js:478:10)                                            
    at Module.load (module.js:355:32)                                                              
    at Function.Module._load (module.js:310:12)                                                    
    at Module.require (module.js:365:17)                                                           
    at require (module.js:384:17)                                                                  
    at Object.<anonymous> (C:\Users\MatheusDavidson\www\rcl\server\api\cep\index.js:3:18)          
    at Module._compile (module.js:460:26)                                                          
```

**Comment by wagoid** [comment]
Qual a versão do seu Node.js? Nas versões anteriores à 4, variáveis let e const não são permitidas por padrão.
